# permissions to do viewer stsbugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsbug-viewer-role
rules:
- apiGroups:
  - demo.mortent.no
  resources:
  - stsbugs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.mortent.no
  resources:
  - stsbugs/status
  verbs:
  - get
