# permissions to do edit stsbugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsbug-editor-role
rules:
- apiGroups:
  - demo.mortent.no
  resources:
  - stsbugs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.mortent.no
  resources:
  - stsbugs/status
  verbs:
  - get
  - patch
  - update
